export const services = [
  {
    id: '1',
    name: 'تلگـرام',
    name_en: 'Telegram',
    description: '',
    image: '/images/sv/telegram.svg',
    active: '1',
    emoji: '💎',
  },
  {
    id: '2',
    name: 'اینستاگرام',
    name_en: 'Instagram',
    description: '',
    image: '/images/sv/instagram.svg',
    active: '1',
    emoji: '📷',
  },
  {
    id: '3',
    name: 'واتسـاپ',
    name_en: 'whatsapp',
    description: '',
    image: '/images/sv/whatsapp.svg',
    active: '1',
    emoji: '📞',
  },
  {
    id: '4',
    name: 'وایبــر',
    name_en: 'viber',
    description: '',
    image: '/images/sv/viber.svg',
    active: '1',
    emoji: '💡',
  },
  {
    id: '5',
    name: 'ویچت',
    name_en: 'wechat',
    description: '',
    image: '/images/sv/wechat.svg',
    active: '1',
    emoji: '💬',
  },
  {
    id: '6',
    name: 'جیمیل - گوگل - یوتیوب',
    name_en: 'google',
    description: '',
    image: '/images/sv/google.svg',
    active: '1',
    emoji: '🔍',
  },
  {
    id: '7',
    name: 'فیسبـوک',
    name_en: 'facebook',
    description: '',
    image: '/images/sv/facebook.svg',
    active: '1',
    emoji: '📪',
  },
  {
    id: '8',
    name: 'تویتــر',
    name_en: 'twitter',
    description: '',
    image: '/images/sv/twitter.svg',
    active: '1',
    emoji: '🐦',
  },
  {
    id: '9',
    name: 'مایکروسافت',
    name_en: 'microsoft',
    description: '',
    image: '/images/sv/microsoft.svg',
    active: '1',
    emoji: '💻',
  },
  {
    id: '10',
    name: 'لایـن',
    name_en: 'line',
    description: '',
    image: '/images/sv/line.svg',
    active: '1',
    emoji: '📗',
  },
  {
    id: '11',
    name: 'یــاهو',
    name_en: 'yahoo',
    description: '',
    image: '/images/sv/yahoo.svg',
    active: '1',
    emoji: '📨',
  },
  {
    id: '12',
    name: 'دیگـر سرویـس‌ها',
    name_en: 'other',
    description: '',
    image: '/images/sv/other.svg',
    active: '1',
    emoji: '🌐',
  },
  {
    id: '13',
    name: 'بیتـاک',
    name_en: 'beetalk',
    description: '',
    image: '/images/sv/beetalk.svg',
    active: '1',
    emoji: null,
  },
  {
    id: '14',
    name: 'لینکدین',
    name_en: 'linkedin',
    description: '',
    image: '/images/sv/linkedin.svg',
    active: '1',
    emoji: null,
  },
  {
    id: '15',
    name: 'پی پال',
    name_en: 'paypal',
    description: '',
    image: '/images/sv/paypal.svg',
    active: '1',
    emoji: '♾',
  },
  {
    id: '16',
    name: 'فایور',
    name_en: 'fiverr',
    description: '',
    image: '/images/sv/fiverr.svg',
    active: '1',
    emoji: null,
  },
  {
    id: '17',
    name: 'تیندر',
    name_en: 'tinder',
    description: '',
    image: '/images/sv/tinder.svg',
    active: '1',
    emoji: null,
  },
  {
    id: '18',
    name: 'ایمو',
    name_en: 'imo',
    description: '',
    image: '/images/sv/imo.svg',
    active: '1',
    emoji: null,
  },
  {
    id: '19',
    name: 'وبمانی',
    name_en: 'webmoney',
    description: '',
    image: '/images/sv/webmoney.svg',
    active: '1',
    emoji: null,
  },
  {
    id: '20',
    name: 'وی‌کی',
    name_en: 'vk',
    description: '',
    image: '/images/sv/vk.svg',
    active: '1',
    emoji: '📬',
  },
  {
    id: '21',
    name: 'آمازون',
    name_en: 'amazon',
    description: '',
    image: '/images/sv/amazon.svg',
    active: '1',
    emoji: '🔅',
  },
  {
    id: '22',
    name: 'Mail.ru',
    name_en: 'mail.ru',
    description: '',
    image: '/images/sv/mailru.svg',
    active: '1',
    emoji: null,
  },
  {
    id: '23',
    name: 'نت‌فلیکس',
    name_en: 'netflix',
    description: '',
    image: '/images/sv/netflix.svg',
    active: '1',
    emoji: null,
  },
  {
    id: '24',
    name: 'استیم',
    name_en: 'steam',
    description: '',
    image: '/images/sv/steam.svg',
    active: '1',
    emoji: null,
  },
  {
    id: '25',
    name: 'دیسکورد',
    name_en: 'discord',
    description: '',
    image: '/images/sv/discord.svg',
    active: '1',
    emoji: null,
  },
  {
    id: '26',
    name: 'اپـل',
    name_en: 'apple',
    description: '',
    image: '/images/sv/apple.svg',
    active: '1',
    emoji: '',
  },
  {
    id: '27',
    name: 'Qiwi',
    name_en: 'qiwi',
    description: '',
    image: '/images/sv/qiwi.svg',
    active: '1',
    emoji: null,
  },
  {
    id: '31',
    name: '1688.com',
    name_en: '1688.com',
    description: '',
    image: '/images/sv/1688.svg',
    active: '1',
    emoji: null,
  },
  {
    id: '32',
    name: 'بلیـزارد',
    name_en: 'Blizzard',
    description: '',
    image: '/images/sv/blizzard.svg',
    active: '1',
    emoji: null,
  },
  {
    id: '33',
    name: 'تیک تاک',
    name_en: 'tiktok',
    description: '',
    image: '/images/sv/tiktok.svg',
    active: '1',
    emoji: null,
  },
  {
    id: '34',
    name: 'LocalBitcoins',
    name_en: 'LocalBitcoins',
    description: '',
    image: '/images/sv/localbitcoins.svg',
    active: '1',
    emoji: null,
  },
  {
    id: '35',
    name: 'G2A.com',
    name_en: 'G2A.com',
    description: '',
    image: '/images/sv/g2a.svg',
    active: '1',
    emoji: null,
  },
  {
    id: '36',
    name: 'کلاب هاوس',
    name_en: 'Clubhouse',
    description: '',
    image: '/images/sv/clubhouse.svg',
    active: '1',
    emoji: '📣',
  },
  {
    id: '37',
    name: 'Bigo Live',
    name_en: 'Bigo Live',
    description: '',
    image: '/images/sv/Bigo-Live.svg',
    active: '1',
    emoji: null,
  },
  {
    id: '38',
    name: 'QQ',
    name_en: 'Tencent QQ ',
    description: '',
    image: '/images/sv/qq.svg',
    active: '1',
    emoji: null,
  },
  {
    id: '39',
    name: 'Airbnb',
    name_en: 'Airbnb',
    description: '',
    image: '/images/sv/airbnb.svg',
    active: '1',
    emoji: null,
  },
  {
    id: '40',
    name: 'Snapchat',
    name_en: 'Snapchat',
    description: '',
    image: '/images/sv/snapchat.svg',
    active: '1',
    emoji: null,
  },
  {
    id: '41',
    name: 'Alibaba',
    name_en: 'Alibaba',
    description: '',
    image: '/images/sv/alibaba.svg',
    active: '1',
    emoji: null,
  },
  {
    id: '45',
    name: 'سیگنال',
    name_en: 'signal',
    description: '',
    image: '/images/sv/signal.svg',
    active: '1',
    emoji: null,
  },
  {
    id: '46',
    name: 'AliExpress',
    name_en: 'AliExpress',
    description: '',
    image: '/images/sv/aliexpress.svg',
    active: '1',
    emoji: null,
  },
  {
    id: '47',
    name: 'Tango',
    name_en: 'Tango',
    description: '',
    image: '/images/sv/tango.svg',
    active: '1',
    emoji: null,
  },
  {
    id: '48',
    name: 'آدیداس',
    name_en: 'Adidas',
    description: '',
    image: '/images/sv/adidas.svg',
    active: '1',
    emoji: null,
  },
  {
    id: '49',
    name: 'نایکی',
    name_en: 'Nike',
    description: '',
    image: '/images/sv/nike.svg',
    active: '1',
    emoji: null,
  },
  {
    id: '51',
    name: 'ebay',
    name_en: 'ebay',
    description: '',
    image: '/images/sv/ebay.svg',
    active: '1',
    emoji: null,
  },
  {
    id: '52',
    name: 'MEGA',
    name_en: 'MEGA',
    description: '',
    image: '/images/sv/mega.svg',
    active: '1',
    emoji: null,
  },
  {
    id: '53',
    name: 'هواوی',
    name_en: 'huawei',
    description: '',
    image: '/images/sv/huawei.svg',
    active: '1',
    emoji: null,
  },
  {
    id: '54',
    name: 'AliPay',
    name_en: 'AliPay',
    description: '',
    image: '/images/sv/alipay.svg',
    active: '1',
    emoji: null,
  },
  {
    id: '55',
    name: 'Zoho',
    name_en: 'Zoho',
    description: '',
    image: '/images/sv/zoho.svg',
    active: '1',
    emoji: null,
  },
  {
    id: '56',
    name: 'AOL',
    name_en: 'AOL',
    description: '',
    image: '/images/sv/aol.svg',
    active: '1',
    emoji: null,
  },
  {
    id: '57',
    name: 'Skrill',
    name_en: 'Skrill',
    description: '',
    image: '/images/sv/skrill.svg',
    active: '1',
    emoji: null,
  },
  {
    id: '58',
    name: 'Blockchain',
    name_en: 'blockchain',
    description: '',
    image: '/images/sv/blockchain.svg',
    active: '1',
    emoji: null,
  },
  {
    id: '59',
    name: 'Taobao',
    name_en: 'Taobao',
    description: '',
    image: '/images/sv/taobao.svg',
    active: '1',
    emoji: null,
  },
  {
    id: '60',
    name: 'لایکی',
    name_en: 'Likee',
    description: '',
    image: '/images/sv/likee.svg',
    active: '1',
    emoji: null,
  },
  {
    id: '61',
    name: 'Coinbase',
    name_en: 'Coinbase',
    description: '',
    image: '/images/sv/coinbase.svg',
    active: '1',
    emoji: null,
  },
  {
    id: '62',
    name: 'Upwork ',
    name_en: 'Upwork ',
    description: '',
    image: '/images/sv/upwork.svg',
    active: '1',
    emoji: null,
  },
  {
    id: '63',
    name: 'ProtonMail',
    name_en: 'ProtonMail',
    description: '',
    image: '/images/sv/protonmail.svg',
    active: '1',
    emoji: null,
  },
  {
    id: '64',
    name: 'Fastmail',
    name_en: 'Fastmail',
    description: '',
    image: '/images/sv/fastmail.svg',
    active: '1',
    emoji: null,
  },
  {
    id: '65',
    name: 'Gameflip',
    name_en: 'Gameflip',
    description: '',
    image: '/images/sv/gameflip.svg',
    active: '1',
    emoji: null,
  },
  {
    id: '66',
    name: 'TradingView',
    name_en: 'TradingView',
    description: '',
    image: '/images/sv/tradingview.svg',
    active: '1',
    emoji: null,
  },
  {
    id: '68',
    name: 'KakaoTalk',
    name_en: 'KakaoTalk',
    description: '',
    image: '/images/sv/kakaotalk.svg',
    active: '1',
    emoji: null,
  },
  {
    id: '69',
    name: 'Crypto.com',
    name_en: 'cryptocom',
    description: '',
    image: '/images/sv/cryptocom.svg',
    active: '1',
    emoji: null,
  },
  {
    id: '70',
    name: 'odnoklassniki',
    name_en: 'odnoklassniki',
    description: '',
    image: '/images/sv/odnoklassniki.svg',
    active: '1',
    emoji: null,
  },
  {
    id: '71',
    name: 'Mamba',
    name_en: 'Mamba',
    description: '',
    image: '/images/sv/mamba.svg',
    active: '1',
    emoji: null,
  },
  {
    id: '72',
    name: 'Open AI | ChatGPT',
    name_en: 'open ai',
    description: '',
    image: '/images/sv/openai.svg',
    active: '1',
    emoji: '🤖',
  },
  {
    id: '73',
    name: 'kaggle',
    name_en: 'kaggle',
    description: '',
    image: '/images/sv/kaggle.svg',
    active: '1',
    emoji: null,
  },
]
